[package]
name = "serde-splunk"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
quick-xml = { version = "0.37.0", features = ["serialize"] }
serde = { version = "1.0.215", features = ["derive"] }
tokio = { version = "1.41.1", features = ["full"] }
